### PR TITLE
Beyondverbal tone analyzer

### PR DESCRIPTION
**Pull request by dingoflamingo**
implements voice analysis
-hover over the text to see what emotions were analyzed during the speech

fixed word frequency
-fixed bug where unintended spaces appearing in transcript 
-fixed bug where words like "doesn't" would result in a Uncaught SyntaxError for Word Frequency analyzer due to unescaped apostrophe
-changed css slightly to implement voice analysis

### CODE REVIEW

**Comment by hhu94** [comment]
I added the EMOTION_API_KEY to travis, builds should pass now.

Edit: actually, there is a bug in Recording.create, fixing it.

Edit 2: fixed, build passes now.

**Comment by hhu94** [comment]
I tried feeding in the a speech by Obama I found on youtube and it seems that the whole resulting transcript is one hover "section". What I mean is that the description of the tone is not separated into different sections, but it's one description for the whole transcript.

**Comment by hhu94** [comment]
Unit tests for this section would be appreciated.

**Comment by williambhot** [comment]
I tested this as well. It is properly separated into different hover sections for me. However, it is a bit difficult to tell where they end and begin (from the users point of view) so it would be nice to style the spans so that the user can tell
screen shot 2016-12-02 at 13 45 41

**Comment by hhu94** [comment]
This is pretty neat, nice job!

Once we have tests and those pass, I think we can merge this.

**Pull request merged**
